#!/usr/bin/env python3
"""Regenerate the small offline lexicon from a pinned MIT-licensed CSpell snapshot.
Network is used only by this maintainer script, never by the application.
"""
from pathlib import Path
from urllib.request import urlopen
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parent.parent
REVISION = '152f3ba420772105156cd0ead94a47f9ed493a8d'
BASE = f'https://raw.githubusercontent.com/streetsidesoftware/cspell-dicts/{REVISION}/dictionaries/'
SOURCES = {
    'companies/src/companies.txt': 'names',
    'software-terms/src/software-tools.txt': 'names',
    'software-terms/src/software-services.txt': 'names',
    'software-terms/src/network-os.txt': 'names',
    'software-terms/src/software-terms.txt': 'terms',
    'software-terms/src/coding-terms.txt': 'terms',
    'software-terms/src/computing-acronyms.txt': 'terms',
    'filetypes/src/filetypes.txt': 'terms',
}
# Native dictionaries accept these common words as lowercase. They must not acquire
# company capitalization just because a company list contains the same spelling.
# Broader native-dictionary checks in NameLexicon also protect ordinary words.
AMBIGUOUS = set('apple adobe amazon notion slack zoom word excel outlook access teams pages numbers keynote pages brave arc spark bear craft linear raycast warp rectangle magnet transmission things ray shell target square box meta oracle canon dell mint signal telegram opera edge safari chrome firefox discord steam unity unreal blender sketch fig jam notion notionlabs snap epic coral stripe buffer make postman post woman man monday frontier gap next national international group holdings corp corporation company limited inc ltd plc pty healthcare mastercard'.split())

buckets = {'names': set(), 'terms': set()}
manifest = {'repository': 'https://github.com/streetsidesoftware/cspell-dicts', 'revision': REVISION, 'sources': {}}
for path, kind in SOURCES.items():
    data = urlopen(BASE + path, timeout=30).read()
    manifest['sources'][path] = {'sha256': hashlib.sha256(data).hexdigest(), 'bytes': len(data)}
    for line in data.decode().splitlines():
        line = line.split('#')[0].strip()
        if kind == 'names':
            buckets[kind].update(re.findall(r'(?<![\w.-])[A-Za-z]{3,32}(?![\w.-])', line))
        elif re.fullmatch(r'[A-Za-z]{2,32}', line):
            buckets[kind].add(line)

# Variants with conflicting capitalization are recognition-only, never arbitrarily chosen.
variants = {}
for word in buckets['names']:
    variants.setdefault(word.lower(), set()).add(word)
canonical = sorted(next(iter(v)) for k, v in variants.items()
                   if len(v) == 1 and k not in AMBIGUOUS and next(iter(v)) != k and len(k) >= 4)
known = sorted({w.lower() for w in buckets['names'] | buckets['terms']})
header = '// Generated by scripts/update-lexicon.py. Do not edit.\n// CSpell MIT data; see THIRD_PARTY_NOTICES.md and docs/lexicon-sources.json.\n'
output = header + 'enum BundledLexicon {\n'
for name, entries in [('canonicalNames', canonical), ('recognizedTerms', known)]:
    output += f'    static let {name}: [String] = """\n' + '\n'.join(entries) + '\n""".split(separator: "\\n").map(String.init)\n'
output += '}\n'
(ROOT / 'Sources/AutoCorrectCore/BundledLexicon.generated.swift').write_text(output)
manifest['canonicalNameCount'] = len(canonical)
manifest['recognizedTermCount'] = len(known)
(ROOT / 'docs/lexicon-sources.json').write_text(json.dumps(manifest, indent=2) + '\n')
license_text = urlopen(BASE + 'companies/LICENSE', timeout=30).read().decode()
for package in ['software-terms', 'filetypes']:
    assert urlopen(BASE + package + '/LICENSE', timeout=30).read().decode() == license_text
(ROOT / 'THIRD_PARTY_NOTICES.md').write_text('# Third-party word data\n\nSelected company, software, coding, and file-type words are derived from [CSpell dictionaries](https://github.com/streetsidesoftware/cspell-dicts) at commit `' + REVISION + '`. The generated data filters unsupported tokens, omits ambiguous/conflicting names from automatic casing, and retains lowercase recognition terms. This app does not bundle or run CSpell itself.\n\n' + license_text)
print(f'Generated {len(known)} recognition terms and {len(canonical)} canonical names ({len(output.encode())} bytes of Swift source).')
